language: cpp
compiler:
  - gcc
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
before_install:
 - sudo apt-get update
 - sudo apt-get install liblinear-dev
 - sudo apt-get install libgtest-dev
 - sudo apt-get install doxygen
 - cd /usr/src/gtest
 - sudo cmake CMakeLists.txt
 - sudo make
 - sudo cp *.a /usr/lib
 - cd -
script:
 - bash run.sh
 - bash runTest.sh
 - bash runDocs.sh
 - bash runClean.sh