language: cpp
before_install:
 - sudo apt-get update
 - sudo apt-get install liblinear-dev
 - sudo apt-get install libgtest-dev
 - sudo apt-get install doxygen
 - cd /usr/src/gtest
 - sudo cmake CMakeLists.txt
 - sudo make
 - sudo cp *.a /usr/lib
 - cd -
script:
 - make
 - cp ./externals/liblinear-1.94/*.h ./bridge/include
 - cp ./externals/EasyBMP/include/*.h ./bridge/include
 - cp ./externals/argvparser/include/*.h ./bridge/include
 - bash run.sh
 - bash runTest.sh
 - bash runDocs.sh
 - bash runClean.sh